[workspace]
authors = ["inwonakng <inwon.kang04@gmail.com>"]
channels = ["conda-forge"]
name = "configkit"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pyyaml = ">=6.0" # Added pyyaml

[host-dependencies]
pytest = ">=8.4.1,<9"